const names = require('./2-names')
const sayHi = require('./3-utils')
// console.log(names)
const data = require('./4-alternative')
require('./5-mind-grenade')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)